### PR TITLE
AJAX errors, spinners, and various UI changes

### PR DESCRIPTION
**Pull request by valendesigns**
- [x] AJAX requests should be converted to use `wp_send_json_error` and `wp_send_json_success` instead of `wp_die` to return a response for proper error handling.
- [x] `submitDelete` should only remove the menu from the UI on success, it currently does regardless of the response.
- [x] Fix the menu delete UI
- [x] Fix spinners

### CODE REVIEW

**Comment by voldemortensen** [comment]
Ah, I missed that you had taken it out.

**Comment by valendesigns** [comment]
How do I fix these failed Travis tests? they all seem to be related to unused JS variables.

**Comment by westonruter** [comment]
@valendesigns 

Replace this:

```js
		/**
		 * @since Menu Customizer 0.3
		 *
		 * @param {String} id
		 * @param {Object} options
		 */
		initialize: function ( id, options ) {
			var container = this;
			container.contentEmbedded = false;

			api.Section.prototype.initialize.apply( this, arguments );
		},
```

```js
		/**
		 * @since Menu Customizer 0.3
		 */
		initialize: function () {
			var container = this;
			container.contentEmbedded = false;
			api.Section.prototype.initialize.apply( this, arguments );
		},
```

Or with this:

```js
		/**
		 * @since Menu Customizer 0.3
		 *
		 * @param {String} id
		 * @param {Object} options
		 */
		initialize: function ( id, options ) {
			var container = this;
			container.contentEmbedded = false;

			api.Section.prototype.initialize.call( this, id, options );
		},
```

**Comment by westonruter** [comment]
Same goes for the `onChangeExpanded` method.

**Comment by westonruter** [comment]
And then add `alert` to the top of the file among:

```js
/* global _wpCustomizeMenusSettings, confirm */
```

**Comment by valendesigns** [comment]
Thank you, I'll get that updated. Though, where is `arguments` being set? It's passed but is not instantiated anywhere.

**Comment by valendesigns** [comment]
Sweet, build passes now!

**Comment by westonruter** [comment]
> Thank you, I'll get that updated. Though, where is arguments being set? It's passed but is not instantiated anywhere.

The `arguments` variable is a JS magic variable: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments

Note that it is deprecated.

**Comment by valendesigns** [comment]
Yeah, I figured as much right after I asked. Removing it seemed like the more logical choice to me, and being it's deprecated likely was the way forward. Happy coincidence. Thanks for the help, as well. 

Hopefully everyone likes the changes I've made. I'm going to go get some sleep so if something needs to be changed on my end it will not be until tonight. Cheers Guys!

**Comment by celloexpressions** [comment]
Sorry about those errors I introduced - was working offline and unsure of the difference between the two (both are used in core I think). Testing this now.

**Comment by celloexpressions** [comment]
Regarding the new delete menu UI, I'd specifically like to avoid having a delete button in proximity to the add-item buttons or any other common flows. When it comes down to it, menu deletion is an edge case, since there's nothing wrong with have a bunch of unused menus, so while we need to support it somehow, it shouldn't be prominent.

**Comment by celloexpressions** [comment]
Other than that, this looks good. I'm still thinking a select for menu-deletion after the menu-addition stuff in the add new menu section would probably be the best bet. Once menu-delete is resolved this can be merged.

**Comment by valendesigns** [comment]
IMO separating the ability to delete a menu from the actual menu itself is really bad UX. Having a dropdown or button in the add new menu area is very confusing. It didn't pass the wife test. She couldn't delete a menu until I change it. We can move it away from the add new items button by floating it left, though moving it out of the menu causes user frustration.  Also when the customized changes it will get even more obscure of an option because the user will have to go back and click add new menu to delete a menu. That is not intuitive at all.

**Comment by celloexpressions** [comment]
Let's put it on the left for now and keep thinking about it. It isn't the best UX, but I'd like to de-emphasize it as much as possible because it doesn't need to be a commonly-used feature. It would also help to only show it if the current menu isn't in any locations (would need to update that in JS too when locations are changed).

**Comment by valendesigns** [comment]
Fixed. I agree that we can improve on it. Something we'll have to address soon. I like the idea of not allowing them to delete it if it's in use.

**Pull request merged**
