### PR TITLE
Re-implement accessible touch-friendly reordering

### LINKED ISSUE #111: Finish re-implementing accessible touch-friendly reordering
With the re-architecture of the Customizer settings in #67 (PR #73), the way that menus and their items are represented became incompatible with the previous implementation of the functionality. Now that all of the items have their settings data stored in memory, we can update the reordering controls to just manipulate the models and the controls in the menu need to then reflow to their proper locations. 

This is split out from #4.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #111

### CODE REVIEW

**Comment by westonruter** [comment]
@designsimply please review

**Comment by valendesigns** [comment]
Great work on this! Moving the menu items and their children around works nicely. Though I have found two issue that are blockers for me. The first being that any levels below 7 have a terrible UI when using the keyboard navigation, which is likely due to the change from a 15px to a 20px indention. We need to revert that. Second, is that menus are loading with orphaned menu items. The screen shot shows both issues.

orphaned

**Comment by valendesigns** [comment]
We could potentially make it `15px` only when sorting, as well. So it may not need to be completely reverted back.

**Comment by westonruter** [comment]
@valendesigns:

> Second, is that menus are loading with orphaned menu items. 

Good catch. This is fixed in 24ebd56.

**Comment by westonruter** [comment]
@valendesigns and I've implemented a 15px indent when reordering in 301cb2c.

**Comment by valendesigns** [comment]
This looks good to me, should we merge or do we need others to sign off still?

**Pull request merged**
